version: '3.8'

services:
  db:
    image: postgres:latest # Il nome del Dockerfile (opzionale se è chiamato "Dockerfile")
    container_name: Database
    environment:
      POSTGRES_PASSWORD: adminPW
      POSTGRES_USER: postgres
      POSTGRES_DB: SoundSphereDB
    volumes:
      - ./DBdata:/var/lib/postgresql/data  # Monta tutta la directory dei dati
    ports:
      - "5432:5432"
    networks:
      - app_network  # Aggiungi il servizio db alla rete comune

  backend:
    build: .
    container_name: springbootbackend
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Monta la cartella del progetto come volume

    networks:
      - app_network  # Collega il backend alla rete comune

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
    name: app_network
