server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: webapp
  datasource:
    url: jdbc:postgresql://Database:5432/SoundSphereDB
    username: postgres
    password: adminPW
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect