server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: webapp

  datasource:
    url: jdbc:postgresql://Database:5432/SoundSphereDB
    username: postgres
    password: adminPW
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Disabilita l'auto aggiornamento dello schema di Hibernate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true  # Abilita Liquibase
    change-log: classpath:/db/changelog/db.changelog-master.xml  # Percorso al file di changelog di Liquibase

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: false

app:
  filiale:
    online:
      name: OnlineStore
  static-data:
    renewal-duration: DURATA_RINNOVO_RUOLO